const areas = [
  "Climatologia, clima",
  "Geoquímica, Geofísica",
  "Mineralogia",
  "Paleontologia",
  "Ciências planetárias",
  "Geologia",
  "Sismologia",
  "Oceanografia",
  "Álgebra",
  "Matemática analítica",
  "Matemática aplicada",
  "Geometria",
  "Probabilidade e Estatística",
  "Átomos, moléculas e sólidos",
  "Física Biológica",
  "Instrumentação e eletrônica",
  "Magnetismo e Eletromagnetismo",
  "Física de partículas e nuclear",
  "Óptica, Laser",
  "Acústica",
  "Física teórica, astronomia",
  "Elétrica Geral",
  "Geração, transmissão e transformação de energia elétrica",
  "Acionamentos elétricos",
  "Energias Renováveis",
  "Mecânica Geral",
  "Eng. industrial",
  "Desenvolvimento de veículos",
  "Desenvolvimento de produtos e processos",
  "Biorremediação",
  "Gerenciamento de ecossistemas",
  "Eng. Ambiental",
  "Gerenciamento de recursos terrestres, hídricos e florestais",
  "Gerenciamento de resíduos, reciclagem",
  "Política ambiental, legislação ambiental",
  "Educação ambiental",
  "Diagnóstico e tratamento de doenças",
  "Epidemiologia",
  "Genética",
  "Nutrição",
  "Fisiologia e Fisiopatologia",
  "Saúde no Trabalho",
  "Prevenção, profilaxia"
];

export default areas;
